USE GROUP_BY;
SELECT * FROM PIVOT;
-- FIND THE TOTAL SALES BY ITEM TYPES-- 
SELECT ITEM_TYPE, round(SUM(ITEM_OUTLET_SALES),0) AS TOTAL_SALES FROM PIVOT 
GROUP BY ITEM_TYPE 
ORDER BY TOTAL_SALES DESC;
-- FIND THE TOTAL AVERAGE BY OUTLET TYPE-- 
SELECT OUTLET_TYPE, round(AVG(ITEM_OUTLET_SALES),0) AS TOTAL_AVG FROM PIVOT 
GROUP BY OUTLET_TYPE;
 -- FIND THE COUNT OF THE ITEM_FAT CONTENT AND FILTER OUT_LOW FAT-- 
 SELECT ITEM_FAT_CONTENT,COUNT(ITEM_OUTLET_SALES) FROM PIVOT
 GROUP BY ITEM_FAT_CONTENT 
 HAVING NOT ITEM_FAT_CONTENT ="LOW FAT"; 
 -- FIND THE TOTAL _SALES BY ITEM _TYPE AND ITEM_FAT CONTENT-- 
 SELECT ITEM_TYPE,ITEM_FAT_CONTENT,ROUND(SUM(ITEM_OUTLET_SALES),0) FROM PIVOT 
 GROUP BY ITEM_TYPE,ITEM_FAT_CONTENT;
 
 